# Generated by Django 4.2.2 on 2023-06-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='ReadIt', max_length=100),
        ),
    ]
