# Generated by Django 4.2.2 on 2023-06-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_postviews_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postViews',
            new_name='views',
        ),
    ]
