# Generated by Django 4.2.2 on 2023-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_postviews_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('us', 'U.S.'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('opinion', 'Opinion'), ('science', 'Science'), ('programming', 'Programming'), ('style', 'Style'), ('travel', 'Travel')], max_length=50),
        ),
    ]
