# Generated by Django 4.2.2 on 2023-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('miscellaneous', 'Miscellaneous'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('opinion', 'Opinion'), ('science', 'Science'), ('programming', 'Programming'), ('style', 'Style'), ('travel', 'Travel')], max_length=50),
        ),
    ]
