# Generated by Django 4.2.2 on 2023-06-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
