# Generated by Django 4.2.2 on 2023-06-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
